mesh:
  type: SquareMesh
  parameters:
    nx: 8
    ny: 8
    L: 1

r: 50

function_space:
  family: 'CG'
  degree: 2

nitsche:
  r0: 1e6

sub_domain: [1, 2, 3, 4]
f: ['0', '0', '0']
g: ['x[0]', 'x[1]', '0']
phi: [['1', '0'], ['0', '1'], ['0', '0']]
